$ErrorActionPreference = "Stop"
New-Item -ItemType Directory -Force -Path "stitch_downloads"

Write-Host "Downloading Screen 1: Bookshelf - Updated Navigation"
curl.exe -L "https://lh3.googleusercontent.com/aida/ADBb0uipHTijx9Q0ShuLd-WQDrYk9wW3esrwSjwLTAbtGDbl73AWmVy-J6gkWjvYlpb_vMf7EhMJoJppgb-D69F1JCgfK2Omyf90Aefwmpc8HijeZWjnhlgQfyoFmSEcOhYAfbG-Mn8wf0BcpP9WawoUV302rAj5HIvLMCy3fCXW2A5nb6FBkqDulhOgBt-sxbaZ1xmlYltsmMC78EkBlIN9J_G_Kb_AFZc-STn6pjs1H48b-ZIPiULIFdKdekCO" -o "stitch_downloads\1_Bookshelf_Updated_Navigation.png"
curl.exe -L "https://contribution.usercontent.google.com/download?c=CgthaWRhX2NvZGVmeBJ8Eh1hcHBfY29tcGFuaW9uX2dlbmVyYXRlZF9maWxlcxpbCiVodG1sX2Q2MDI0OGEzMmU2YjQ0OGU4YWMwMWQ1MjA4ZGRmZjA0EgsSBxDa9vba5AkYAZIBJAoKcHJvamVjdF9pZBIWQhQxMTQzNjAwMTAyNjU5MTAwNTI2Mw&filename=&opi=89354086" -o "stitch_downloads\1_Bookshelf_Updated_Navigation.html"

Write-Host "Downloading Screen 2: Home Carousel - Updated Navigation"
curl.exe -L "https://lh3.googleusercontent.com/aida/ADBb0uhmnEFyqncjuFnv6V3hZj6hBsm_zFaQ5WKzoaBXjeIGlhVrI9XBglLapGEsKAYzXTaW4FAuW51aadgtQ3a9fmMMMSEtU70tuc_S7UzfepPrgWgmQGmbCyIOkUG-1pHEXgwvIPzRMiIJLj8pjlSaJ5cbDb3h8FCenipau-TuH0qD7mIavOo0BuPpstUsmOY_Zlmr3sQeM8ft53Z4ZIFG4YcLhTiV5YgHIiiFv_6QgVOhYw3GFRz1kkHUmXDD" -o "stitch_downloads\2_Home_Carousel_Updated_Navigation.png"
curl.exe -L "https://contribution.usercontent.google.com/download?c=CgthaWRhX2NvZGVmeBJ8Eh1hcHBfY29tcGFuaW9uX2dlbmVyYXRlZF9maWxlcxpbCiVodG1sX2JiZTE0ZTgzZTE3ODQ3NzM4OWQ1MjNkM2NjYTI5Y2M1EgsSBxDa9vba5AkYAZIBJAoKcHJvamVjdF9pZBIWQhQxMTQzNjAwMTAyNjU5MTAwNTI2Mw&filename=&opi=89354086" -o "stitch_downloads\2_Home_Carousel_Updated_Navigation.html"

Write-Host "Downloading Screen 3: Create New Item"
curl.exe -L "https://lh3.googleusercontent.com/aida/ADBb0ugPBU0PAphISs3W0BdFgiERLVtHwOfw95vlmkdC9XAulsrsH1ZarILshc4lVDLwPiwep0CMHo6davpD1pSCGEQAStex6FtIiuf2rqM8ITqnvPnpKsWcgnUHkT8iZtdsO_tWcMx4mFKRn0fn7FfSTACurGS387HDHg7AO5TG9iQ1K9bN3AldsqmjsmBm2FzIpRqJWyP0exVagJuUaXr0IK9Mldapzd1rhw3J6aEfz1e01LLJ8oj-BY8qkygx" -o "stitch_downloads\3_Create_New_Item.png"
curl.exe -L "https://contribution.usercontent.google.com/download?c=CgthaWRhX2NvZGVmeBJ8Eh1hcHBfY29tcGFuaW9uX2dlbmVyYXRlZF9maWxlcxpbCiVodG1sXzBhMmE0ODRlMGM3ZTQ3NjhiNWQ2MjRmYmMwOTkyZjQ0EgsSBxDa9vba5AkYAZIBJAoKcHJvamVjdF9pZBIWQhQxMTQzNjAwMTAyNjU5MTAwNTI2Mw&filename=&opi=89354086" -o "stitch_downloads\3_Create_New_Item.html"

Write-Host "Downloading Screen 4: Refined Showcase List"
curl.exe -L "https://lh3.googleusercontent.com/aida/ADBb0uj_FM5MjLmOacaOOSnnEmPKNbi3pQj-8GKu8rpEAoH1tBMMWZMee3Sfo9PKmZlrcXTulx_hlAQ64oNJQzePmaYfREFt454Y8x3x699FgPamNVp1gdIVswhkeExsqgxA6gSSkKLnegu9pmdS3mfO5fKd1F2RF76O6-m7RRlNyyxFcxox57QgCZah3ys2ZhC57z8UXs28MgXvnJ_J4yTOzx-z3StHAHCLA7E4Nk8VV5WkZWHfV9hTpvZIlnT9" -o "stitch_downloads\4_Refined_Showcase_List.png"
curl.exe -L "https://contribution.usercontent.google.com/download?c=CgthaWRhX2NvZGVmeBJ8Eh1hcHBfY29tcGFuaW9uX2dlbmVyYXRlZF9maWxlcxpbCiVodG1sXzZlODBkZjUwMzQzMzQyZmViY2U4MTllYzc1YWQzNTI2EgsSBxDa9vba5AkYAZIBJAoKcHJvamVjdF9pZBIWQhQxMTQzNjAwMTAyNjU5MTAwNTI2Mw&filename=&opi=89354086" -o "stitch_downloads\4_Refined_Showcase_List.html"

Write-Host "Downloading Screen 5: Social Feed"
curl.exe -L "https://lh3.googleusercontent.com/aida/ADBb0uiLvPqL6l8znpHpm70QUK42WA6k0MNtm2zVQR4OgIGrJhtbn4-VXy78ayaG-ELE-I1MCAAb0NAsEOmPlpnfv-CCgGsbR87387QAddzq_hdn-iCw07ENjnJC6fEQ7dKWmcLQ5AVY9nFczM17QXPU9JbqH2zGrlAo5gUxMzxHib33R2Sz0UncsKkrKN6lE_GGyBZ41U7xLZ9ritEVR9h5ovhcBRAE2f1eHBOj0IKbyYNxKvrcVRwbQ3qxBgzh" -o "stitch_downloads\5_Social_Feed.png"
curl.exe -L "https://contribution.usercontent.google.com/download?c=CgthaWRhX2NvZGVmeBJ8Eh1hcHBfY29tcGFuaW9uX2dlbmVyYXRlZF9maWxlcxpbCiVodG1sX2Q4ZGRiNTFlNWYzNzQ3Y2M4YzUyZTA3N2FjYWVjMmUyEgsSBxDa9vba5AkYAZIBJAoKcHJvamVjdF9pZBIWQhQxMTQzNjAwMTAyNjU5MTAwNTI2Mw&filename=&opi=89354086" -o "stitch_downloads\5_Social_Feed.html"

Write-Host "Downloading Screen 6: Redesigned User Profile"
curl.exe -L "https://lh3.googleusercontent.com/aida/ADBb0ui1P_lT2MxqqaRk8q-Xw2WHaY_SM_JJ7iMELXr3z1YRtLXZqxjMujUK8YYOi7QDvbyJGu_iCo8FqNl56wp9HyAZW_FebyadsRLxkLrPrgzx28kLoNvZohnTyKMUlDtZdbfyrTYYLly93wcdmZDo5pOHABHDUKgcQR6nKXG5PX8gPt6rLcXK9wfKRToZ11krBx-o5xtfN6JbidKhP5jUBI_m0cubzt_unYxIfjtIJ4qD4dtpgSOfxO_TmCl9" -o "stitch_downloads\6_Redesigned_User_Profile.png"
curl.exe -L "https://contribution.usercontent.google.com/download?c=CgthaWRhX2NvZGVmeBJ8Eh1hcHBfY29tcGFuaW9uX2dlbmVyYXRlZF9maWxlcxpbCiVodG1sXzIwYTU0NGEyNWUyMjQ3ZDVhZmFlYmVlZGJhMmJmMGQ5EgsSBxDa9vba5AkYAZIBJAoKcHJvamVjdF9pZBIWQhQxMTQzNjAwMTAyNjU5MTAwNTI2Mw&filename=&opi=89354086" -o "stitch_downloads\6_Redesigned_User_Profile.html"

Write-Host "Downloading Screen 7: Refined Item Details - Provenance Fix"
curl.exe -L "https://lh3.googleusercontent.com/aida/ADBb0ujXJ_hJEdOkIf-7tg1s76B1WMPh0ynDG1LAPLz3P-ARozuveqsgeXMjIJdbPsIRkOhMqpIaFyKxUgRZwfBG6iACWjopm2g1sGL9M5xhVV5BGe7_GZBaF2ypV0NuILcIoEG5sv1a7CTM11qTWzkjlV52mgb_q9_b6ipXuGKRI4c_vrzjReM28cwHHysoBuJL8rdFbt_phmKIo9ojfF9lrs2bP5Z-6JCiJwA0aWhGYDRL7k-EM8-mfBuBDXJ9" -o "stitch_downloads\7_Refined_Item_Details_Provenance_Fix.png"
curl.exe -L "https://contribution.usercontent.google.com/download?c=CgthaWRhX2NvZGVmeBJ8Eh1hcHBfY29tcGFuaW9uX2dlbmVyYXRlZF9maWxlcxpbCiVodG1sXzY3MTU4YjIwYWE2OTQwMGM4ZTgxNjdmMjExOWY4ZThkEgsSBxDa9vba5AkYAZIBJAoKcHJvamVjdF9pZBIWQhQxMTQzNjAwMTAyNjU5MTAwNTI2Mw&filename=&opi=89354086" -o "stitch_downloads\7_Refined_Item_Details_Provenance_Fix.html"

Write-Host "Downloads completed."
